library(KoNLP)
library(wordcloud)
txt<-readLines("noh.txt")
nouns<-sapply(txt, extractNoun,USE.NAMES = F)
head(unlist(nouns),30)
nouns<-Filter(function(x){nchar(x)>=2},unlist(nouns))
write(unlist(nouns),'noh_2.txt')
rev<-read.table('noh_2.txt')
nrow(rev)
wordcount<-table(rev)
head(sort(wordcount,decreasing = T),30)
library(RColorBrewer)
palete<-brewer.pal(9,"Set1")
wordcloud(names(wordcount),freq=wordcount,scale=c(5,0,5),rot.per=0.25,min.freq=1,random.order = F,random.color = T,colors=palete)
